name: 'Aggregate Worker'
description: 'Aggregate files from a worker'
inputs:
  stage:
    type: string
    required: true
  worker:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch results of ${{ inputs.worker }}
      id: restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.REPO }}
        key: apt-repo-${{ inputs.stage }}-${{ inputs.worker }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          apt-repo-${{ inputs.stage }}-${{ inputs.worker }}-${{ github.sha }}-${{ github.run_id }}
    - name: Aggregate files
      shell: bash
      if: steps.restore.outputs.cache-matched-key != ''
      run: |
        cat ${{ env.REPO }}/pkg_build_status.csv >> ${{ env.AGG }}/pkg_build_status.csv
        cat ${{ env.REPO }}/sources_exact.repos |
          if [ -f ${{ env.AGG }}/sources_exact.repos ]; then
            tail -n+2 # skip "repositories:"
          else
            cat
          fi | tee -a ${{ env.AGG }}/sources_exact.repos
        rm -f ${{ env.REPO }}/pkg_build_status.csv ${{ env.REPO }}/sources_exact.repos ${{ env.REPO }}/local.yaml
        mv ${{ env.REPO }}/* ${{ env.AGG }}
